### ISSUE TITLE
Definir formato da apresentação

### ISSUE THREAD

**Issue by marlonbernardes** [codeheaven-io/talks#2]
Vamos usar keynote? Ou fazemos os slides em markdown?

**Comment by rafaeleyng** [comment]
Acho que podíamos começar em markdown. Depois decidimos onde vamos fazer.
De qualquer forma, se fizermos slides, vai demorar para fazer a parte visual, então é bom deixarmos isso para outra hora e nos focarmos primeiro no conteúdo. Em markdown.

**Comment by marlonbernardes** [comment]
@rafaeleyng pode ser.
